#!/usr/bin/env bash
# encoding utf-8
# Created by: Acr4n1us
# Contact & Changelog: https://github.com/RamalhoSec
# Bitcoin: 3DppKRbA9Um3z4wnmVtkqnETnvwsip7WkC
# Version 0.1



#::seting terminal colors
black=$(tput bold; tput setaf 0)
red=$(tput bold; tput setaf 1)
green=$(tput bold; tput setaf 2)
yellow=$(tput bold; tput setaf 3)
blue=$(tput bold; tput setaf 4)
magenta=$(tput bold; tput setaf 5)
cyan=$(tput bold; tput setaf 6)
white=$(tput bold; tput setaf 7)
reset=$(tput sgr0)
#:::::::::::::::::::::::::

iface=$2
mon=$1

#::verifications for start
[ "$UID" != "0" ] && { printf "${blue}Ok, run this at root!${reset}\n"; exit 1 ;}
#::::::::::::::::::::::::::


iw dev $mon del
printf "${blue}${mon} was removed!!${reset}\n"
